# Generated by Django 4.1.2 on 2024-05-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_alter_comment_body_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='product',
            new_name='post',
        ),
    ]
